### ISSUE TITLE
Have problem after upgrade HA 0.88.1

### ISSUE THREAD

**Issue by clementchik0308** [thomasloven/lovelace-popup-card#10]
After upgrade to HA 0.88.1 found the button is too big and the width of popup card is not enough. Is there any way to adjust the width of the popup card?

**Comment by iantrich** [comment]
Button? The exit button?

**Comment by clementchik0308** [comment]
I use the popup card to display a custom card and have paper-button without problem, but after upgrade HA, the paper-button changed to mwc-button. The button is too wide and cannot adjusted the width. So would like to check any way to adjust the width of the popup card.

**Comment by thomasloven** [comment]
What button? The X? That's not that type of button, has never been that type of button and has not been replaced with a mwc-button.

Screenshot, please.

**Comment by clementchik0308** [comment]
The button is too wide when changed to mwc-button, you can see the "Hi" button is outside the popup card.

![256ae73c-03ca-4a36-8301-63c56dc4052d](https://user-images.githubusercontent.com/40333001/53340592-59e12f00-3944-11e9-9ed1-b2d233d50ff4.jpg)

**Comment by thomasloven** [comment]
First of all: How ever did you manage to get dirt on your screenshot?

Second. Sorry, there's no way to increase the width of the more-info dialog at this point.
There may be in the next version of popup-card, though. Major overhaul coming up soon.

Also - for future reference - you're using another custom card. That's *always* relevant information for a support request that you should have supplied from the start.
