### ISSUE TITLE
New format still supports all card types?

### ISSUE THREAD

**Issue by cyberjunky** [thomasloven/lovelace-popup-card#13]
I have this popup-card thermostat entry (from a twitch stream of Frenck)
It shows a temp graph and you can open the thermostat by clicking on it.
I cannot seem to convert it to the new format, is this still supported?

```yaml
  - type: custom:mini-graph-card
    entities: sensor.temperatuur_woonkamer
    location_icon: left
    location_state: center
    show:
      fill: false
      extrema: true
    height: 75
    animate: true
    hour24: true
    line_color: var(--primary-color)
    line_color_above: 
      - value: 21
        color: red
    line_color_below:
      - value: 15
        color: white
  - type: custom:popup-card
    entity: sensor.temperatuur_woonkamer
    title: Verwarming
    card:
      type: 'custom:simple-thermostat'
      entity: climate.toon

**Comment by thomasloven** [comment]
Yes, it's still supported.

Please show what you tried and what results you get rather than what you had before starting before the update process.

**Comment by thomasloven** [comment]
When opening this issue, did you *really* select the one "For suggesting new features of popup-card" rather than "For reporting bugs or **unexpected behavior** of popup-card"?
