### ISSUE TITLE
Card leaves a space in layout

### ISSUE THREAD

**Issue by wbilger** [thomasloven/lovelace-popup-card#2]
Would be nice if the space was not there as the card has nothing to do with your layout.
Not sure if is an easy fix, as a workaround is putting the popup-card inside of a custom:vertical-stack-in-card, but not sure if that is ideal.

**Comment by wbilger** [comment]
Actually, I guess I never tested it, putting it in a vertical-card-in-stack gets rid of the space, but then the popup no longer works, so no workaround

**Comment by thomasloven** [comment]
I noticed that too... still thinking about how to best solve it.

In the mean time, I recommend putting any popup-cards as the *last* cards in the view. Then the gap won't be as noticeable...

**Comment by thomasloven** [comment]
Actually... when I think about it, it's a kind of easy thing to fix...
