### ISSUE TITLE
Custom popup not displayed in Chrome Mobile on Android

### ISSUE THREAD

**Issue by brezuicabogdan** [thomasloven/lovelace-popup-card#22]
My Home Assistant version: 0.91.3

My lovelace configuration method (GUI or yaml): yaml

What I am doing: clicking on element with custom popup attached

What I expected to happen: display the customized popup 

What happened instead: the default HA 'more details' popup is displayed

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error



# End of code
```

Error messages from the browser console: cannot see that at this point - working on configuring Chrome Mobiel Debugger via adb

---

`By putting an X in the boxes ([ ]) below, I indicate that I:`

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of popup-card.

[X] Have made sure I am using the latest version of [card-tools](https://github.com/thomasloven/lovelace-card-tools).

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

The popup is displayed correctly and works as expected on all my desktop browsers and on multiple computers. The issue is only with Chrome Mobile on Android devices. I tried it on the latest Chrome version on Android 9 and Android 8.1. At this point I cannot tell you if there are any errors in console on the mobile device browser but working on it. It maybe something related to the way the plugin overrides the default HA popup as the default is shown and not the custom one. I also tried it with the example configuration and the same behavior is observed.

**Comment by thomasloven** [comment]
Can't reproduce the error when following the Minimal steps to reproduce.
