### ISSUE TITLE
Problem with input_select on popup card

### ISSUE THREAD

**Issue by matisaul** [thomasloven/lovelace-popup-card#3]
Hi Thomas,

First of all, thanks for your great work with HA. 

I'm trying to add a input_select in the popup card, but It seems that the options are cutted by the card. In my mobile works great, but in a computer shows in this way:

![image](https://user-images.githubusercontent.com/34925604/50454591-52db7780-0927-11e9-8e7f-0284bd6a79d9.png)

Thanks again!

**Comment by thomasloven** [comment]
This seems to be a problem with Home Assistant.
![more-info select box](https://user-images.githubusercontent.com/1299821/50834281-ebc0b880-1353-11e9-90e2-b615a570029a.jpg)
