### ISSUE TITLE
Popup card not work after home assistant upgrade

### ISSUE THREAD

**Issue by clementchik0308** [thomasloven/lovelace-popup-card#7]
After upgraded to 0.87.0, popup card not working. Got below error:

http://192.168.1.1:8123/local/custom_card/popup-card.js:50:15 TypeError: undefined is not an object (evaluating 'moreInfo.style')

**Comment by webbo1986** [comment]
Iv got the same problem all the other custom_cards Iv got work. Just not the pop up card. Hope someone can help!!!!

**Comment by clementchik0308** [comment]
> After upgraded to 0.87.0, popup card not working. Got below error:
> 
> http://192.168.1.1:8123/local/custom_card/popup-card.js:50:15 TypeError: undefined is not an object (evaluating 'moreInfo.style')

Just change line 49 to
` let moreInfo = document.querySelector("home-assistant")._moreInfoEl;`
 
it works.

**Comment by webbo1986** [comment]
Thanks for the fix, but still getting error.
http://192.168.0.44:8123/local/popup_card.js:50:16 Uncaught TypeError: Cannot read property 'style' of undefined.
any ideas

**Comment by JohanLeirnes** [comment]
Have you changed version in the include?
![skarmavbild 2019-02-08 kl 09 30 06](https://user-images.githubusercontent.com/2168003/52466938-294b7800-2b84-11e9-9fb6-ffdf39cdb6c2.png)

I would need to change the numbers at the end so that lovelace used the updated code.

**Comment by JohanLeirnes** [comment]
But that update did not fix it for me either

Im getting this error now.
```
/local/popup-card.js?v=0.0.11:50:15 TypeError: undefined is not an object (evaluating 'moreInfo.style')
```

**Comment by clementchik0308** [comment]
I use
 ` - url: l/ocal/custom_card/popup-card.js?v=1
     type: js`

**Comment by JohanLeirnes** [comment]
Ok, 

So i updated Card-tools and this popup-card to the latest version and appended the url of the card to a new version so that the browser would read the new javascripts.

Now it works just fine.

So doublecheck that you have the latest version of both and change the version so that the browser re-read the javascripts @webbo1986

**Comment by yabbah** [comment]
Still not work for me. Cant even see that the code is updated in the history? I've updated both popup-card.js and card-tools.js and changed versionnumber in ui-lovelace.yaml.

Do it work for you @webbo1986 ?

**Comment by webbo1986** [comment]
Not had chance to do it. I’m at work at the mo.

**Comment by thomasloven** [comment]
Fixed

**Comment by webbo1986** [comment]
thanks, got it working. 
Use the new popup_card.js file or change line 49 to
` let moreInfo = document.querySelector("home-assistant")._moreInfoEl;`

lovelace config file
 resources:
 - type: js
    url: /local/popup_card.js?v=2
  - type: js
    url: /local/card_tools.js?v=2

clear all caches & restart home assistant.
