### ISSUE TITLE
Scroll Bar on Popup

### ISSUE THREAD

**Issue by myztillx** [thomasloven/lovelace-popup-card#8]
I am getting a scroll bar on the side whenever I use this popup card. Any idea what could be causing this? 

I have tried both mini-graph-card and history-graph and get the same result. I have also played with the settings of mini-graph-card (height and removing title/icon) trying to adjust its height, but still resulted in the scroll bar.

![image](https://user-images.githubusercontent.com/33730898/52649454-5d8da400-2eb6-11e9-8e29-9c0833a72cde.png)

Edit: Sorry, should have added my config as well...

![image](https://user-images.githubusercontent.com/33730898/52650129-a3973780-2eb7-11e9-8a18-aec0d61f6bbf.png)

Edit 2: It seems to go away with an added entity at the bottom. 

![image](https://user-images.githubusercontent.com/33730898/52650712-c5dd8500-2eb8-11e9-8915-96b82386192c.png)

**Comment by myztillx** [comment]
I was able to add your **useful-markdown-card** to this popup. I left the content blank and padding at 0px. to get what is shown below:

![image](https://user-images.githubusercontent.com/33730898/52666515-7d37c300-2edc-11e9-8536-c70015b08383.png)

![image](https://user-images.githubusercontent.com/33730898/52666540-8fb1fc80-2edc-11e9-9e0f-b6f808a1c37c.png)

Thanks for adding so many wonderful and useful cards!

**Comment by vladisnik** [comment]
I changing `overflow-y: auto` to `overflow-y: hidden`, as temporary solution.
In 50th line.
```diff
+ moreInfo.style.overflowY = 'hidden';
- moreInfo.style.overflowY = 'auto';
```
It work better with mini-graph-card now.

**Comment by thomasloven** [comment]
Is this still a problem?

**Comment by myztillx** [comment]
This is no longer a problem. Sorry for the slow reply.
